### PR TITLE
get_Crypto_to_Fiat_Converter.py

### PR DESCRIPTION
**Pull request by smechaab**
This is an example file I think it was missing. I personally use it everyday.
It allows me to check my currencies without logging every 10 minutes on Kraken website, and I find it very useful for development on the Krakenex API (data is dynamically extracted)

This example allows to :
1. Displays the different amount of crypto currencies you own on your Kraken wallet.
2. Displays the total crypto money you own in equivalent fiat money.
3. Adapted to the crypto and fiat currencies you already own.
4. If you don't own any fiat money on your Kraken wallet, it will be displayed the equivalent in USD.
(The fiat money can be easily modified but be aware that some markets doesn't allow it,
DASHUSD -> DASHJPY for example, can't be done because the market doesn't exist on Kraken.
Check k.query_public('Ticker',{'pair': 'YOURMARKET',}) inline to know if it exist.)
5. Works with multi-fiat currencies wallets.

### CODE REVIEW

**Comment by veox** [comment]
Do you have a repo where you develop this?

I would much prefer a link in the README to it. It's rather big, and would require maintenance, which is an overhead I'd like to avoid.

**Comment by smechaab** [comment]
No sorry, I don't have any repo where I developped this. :/
Well, I actually developped this on my personnal free time on my local computer. And I tought it would be interesting to share this with other people using the API.

**Comment by veox** [comment]
Okay then. I'll try and review this at first opportunity.

**Comment by smechaab** [comment]
Alright, contact me if you need anything.

**Comment by veox** [comment]
I've taken another glance. There is a lot of non-trivial indexing, code line count is on par with the base package, and there are some edge cases that will need a lot of maintenance (like the addition of previously non-existent markets on Kraken's side).

I'm afraid this doesn't make a straightforward example of how to use the package, so I'll close this PR.

If you don't want to bother with setting up a repo, it's OK to put in a [gist](https://gist.github.com), and submit a PR linking from `examples/README` (which I will create shortly).

**Pull request closed without merging**
