### PR TITLE
Add examples

### PR DESCRIPTION
**Pull request by AustinDeric**
Addresses issue #10. The following examples are added:
- open-positions.py prints the sum of all open positions
- trades-history.py saves all trade history to a csv file
- form8949.py generates United States IRS tax document form 8949.

### CODE REVIEW

**Comment by veox** [comment]
Skimmed it, looks good!

Question: is the data in `.csv`s yours?

Files in `examples` are blanket-covered by a BSD license. Are you OK with that?

If so, could you sign the commit, mentioning that you're aware of the fact? That would be best.

If you don't want to touch PGP/GPG, a `README.md` can be put in `examples` instead, by you in this PR, or me later on.

**Comment by AustinDeric** [comment]
- Yes, the csv file was mine.  I removed it.
 - Yes, i am ok with the BSD license.  I will update the source file comment's to match the existing example.  I will also sign the commit.

**Comment by veox** [comment]
OK. The request to sign was mostly due to included data that may be considered private. Good call on removing that from git history. :)

**Comment by veox** [comment]
I'll go ahead and merge it as-is.

**Comment by AustinDeric** [comment]
ok, sorry about that, I will issue a PR to make these examples a little better and better documentation.

**Pull request merged**
